name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Tickets'
    labels:
      - 'BLS'
      - 'STS'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  #Changes
  ## What's new?
  $CHANGES
  ## Contributors
  $CONTRIBUTORS