name: Live Deployment

on:
  push:
    branches: [main,test]
permissions:
  contents: read

jobs:
  deploy:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: |
         yarn install
         yarn --frozen-lockfile
      - name: Changelog
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          publish: true
      - name: Deployy
        run: |
          yarn deployy


